### ISSUE TITLE
Any user created from the register module gives out "free admin" in v4

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#394]
### Current Behavior

For anyone reading this: don't worry, your panel is safe (for now), users cannot do anything in the admin panel as they do not have the required permissions to do anything. They can still access some pages, but they can't really do anything with them.

When the speed dial feature is enabled, users who are not admin can see options like: Ask AI or View Tickets, but there are some options that aren't supposed to be there like New User, Create Server, or Create Node.

The image below is from my second account with no admin permissions, where New User, Create Server and Create Node shouldn't be there.

![Image](https://github.com/user-attachments/assets/2b0ad1d2-29ab-4aae-97d6-66db295febde)

### Expected Behavior

The speed dial should show only 2 options: Ask AI if AI is enabled, and View Tickets, if tickets is enabled.

### Steps to Reproduce

1. Enable the speed dial and the register module
2. Register a account from another browser
3. Watch the speed dial show the admin only features

### Panel Version

4.0.0-beta3

### Wings Version

Modified Wings, based on Superdaemon and some modifications

### Error Logs

```bash

```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Fixed in https://github.com/Jexactyl/Jexactyl/commit/43ad811d4e11c803e2210b0d71149b9849d71e15

**Comment by heyitslumi** [comment]
![Image](https://github.com/user-attachments/assets/ae7b855e-539c-4e61-a58a-bf98e12a8324)
![Image](https://github.com/user-attachments/assets/7036edab-bd48-435f-927a-35964295e29b)
The speed dial issue still isn't fixed... for some reason which is why I made this issue
